-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "Project" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "brandName" TEXT NOT NULL DEFAULT '',
    "industry" TEXT NOT NULL DEFAULT '',
    "businessWhat" TEXT NOT NULL DEFAULT '',
    "originStory" TEXT NOT NULL DEFAULT '',
    "idealAudience" TEXT NOT NULL DEFAULT '',
    "audiencePainQuote" TEXT NOT NULL DEFAULT '',
    "audiencePain" TEXT NOT NULL DEFAULT '',
    "whyChooseYou" TEXT NOT NULL DEFAULT '',
    "competitor1" TEXT NOT NULL DEFAULT '',
    "competitor2" TEXT NOT NULL DEFAULT '',
    "competitor3" TEXT NOT NULL DEFAULT '',
    "competitorGap" TEXT NOT NULL DEFAULT '',
    "archetypesSelected" TEXT NOT NULL DEFAULT '[]',
    "value1Always" TEXT NOT NULL DEFAULT '',
    "value1Never" TEXT NOT NULL DEFAULT '',
    "value2Always" TEXT NOT NULL DEFAULT '',
    "value2Never" TEXT NOT NULL DEFAULT '',
    "vpAudience" TEXT NOT NULL DEFAULT '',
    "vpGoal" TEXT NOT NULL DEFAULT '',
    "vpSystem" TEXT NOT NULL DEFAULT '',
    "vibeWord1" TEXT NOT NULL DEFAULT '',
    "vibeWord2" TEXT NOT NULL DEFAULT '',
    "vibeWord3" TEXT NOT NULL DEFAULT '',
    "vibeWord4" TEXT NOT NULL DEFAULT '',
    "headerFont" TEXT NOT NULL DEFAULT 'Anton',
    "bodyFont" TEXT NOT NULL DEFAULT 'Inter',
    "accentFont" TEXT NOT NULL DEFAULT 'Caveat',
    "colorPrimary" TEXT NOT NULL DEFAULT '#1A1A1A',
    "colorSecondary" TEXT NOT NULL DEFAULT '#8A8A86',
    "colorAccent1" TEXT NOT NULL DEFAULT '#E5E5E5',
    "colorAccent2" TEXT NOT NULL DEFAULT '#FFFFFF',
    "darkLightPassYes" BOOLEAN NOT NULL DEFAULT false,
    "darkLightPassNo" BOOLEAN NOT NULL DEFAULT false,
    "darkLightAdj" TEXT NOT NULL DEFAULT '',
    "scalePassYes" BOOLEAN NOT NULL DEFAULT false,
    "scalePassNo" BOOLEAN NOT NULL DEFAULT false,
    "scaleAdj" TEXT NOT NULL DEFAULT '',
    "logoUsageRules" TEXT NOT NULL DEFAULT '',
    "primaryLogoUrl" TEXT,
    "faviconUrl" TEXT,
    "modeTestLightUrl" TEXT,
    "modeTestDarkUrl" TEXT,
    "moodboardImages" TEXT NOT NULL DEFAULT '[null,null,null,null,null,null,null,null]',
    "logoVariations" TEXT NOT NULL DEFAULT '[]',

    CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);
